version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:7.0.4-alpine3.16
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres:alpine3.16
    ports:
      - 5432:5432